# Generated by Django 2.1a1 on 2018-06-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker_rec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechadura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(protocol='ipv4')),
            ],
        ),
    ]
